version: '3'

services:
  app:
    image: talitafesan/webacademy:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "8080:8080"
    network_mode: host
    environment:
      NODE_ENV: production