name: Local Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        id: lint-step
        #continue-on-error: true
        run: npm run lint
      - name: check-lint
        if: failure() && steps.lint-step.outcome == 'failure'
        run: echo "Codigo precisa ser revisto!!"
  build_docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: ./Dockerfile # Specify the path to your Dockerfile here
          tags: talitafesan/webacademy:latest
  deploy:
    needs: lint
    name: Deploy Local Server
    runs-on: self-hosted
    environment: local-deploy
    env:
      IMAGE_NAME: talitafesan/webacademy:latest
      APP_PORT: ${{ secrets.APP_PORT }}
      TS_HOSTNAME: ${{ secrets.TS_HOSTNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Pull and Deploy Container
        run: |
          echo "Deploying on server $TS_HOSTNAME at port $APP_PORT"
          docker pull $IMAGE_NAME
          docker compose down || true
          docker compose up -d
